/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CariRouteImport } from './routes/cari'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDriveRouteImport } from './routes/admin.drive'
import { Route as AdminIklanRouteImport } from './routes/admin.iklan'
import { Route as AdminKomentarRouteImport } from './routes/admin.komentar'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as TagSlugRouteImport } from './routes/tag.$slug'
import { Route as AdminTulisIdRouteImport } from './routes/admin.tulis.$id'
import { Route as ApiPublicGambarSplatRouteImport } from './routes/api/public/gambar.$'
import { Route as ApiPublicGoogleDriveCallbackRouteImport } from './routes/api/public/google-drive/callback'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CariRoute = CariRouteImport.update({
  id: '/cari',
  path: '/cari',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriveRoute = AdminDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIklanRoute = AdminIklanRouteImport.update({
  id: '/iklan',
  path: '/iklan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKomentarRoute = AdminKomentarRouteImport.update({
  id: '/komentar',
  path: '/komentar',
  getParentRoute: () => AdminRoute,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTulisIdRoute = AdminTulisIdRouteImport.update({
  id: '/tulis/$id',
  path: '/tulis/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicGambarSplatRoute = ApiPublicGambarSplatRouteImport.update({
  id: '/api/public/gambar/$',
  path: '/api/public/gambar/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleDriveCallbackRoute =
  ApiPublicGoogleDriveCallbackRouteImport.update({
    id: '/api/public/google-drive/callback',
    path: '/api/public/google-drive/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/cari': typeof CariRoute
  '/admin/drive': typeof AdminDriveRoute
  '/admin/iklan': typeof AdminIklanRoute
  '/admin/komentar': typeof AdminKomentarRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tulis/$id': typeof AdminTulisIdRoute
  '/api/public/gambar/$': typeof ApiPublicGambarSplatRoute
  '/api/public/google-drive/callback': typeof ApiPublicGoogleDriveCallbackRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/cari': typeof CariRoute
  '/admin/drive': typeof AdminDriveRoute
  '/admin/iklan': typeof AdminIklanRoute
  '/admin/komentar': typeof AdminKomentarRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tulis/$id': typeof AdminTulisIdRoute
  '/api/public/gambar/$': typeof ApiPublicGambarSplatRoute
  '/api/public/google-drive/callback': typeof ApiPublicGoogleDriveCallbackRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/cari': typeof CariRoute
  '/admin/drive': typeof AdminDriveRoute
  '/admin/iklan': typeof AdminIklanRoute
  '/admin/komentar': typeof AdminKomentarRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tulis/$id': typeof AdminTulisIdRoute
  '/api/public/gambar/$': typeof ApiPublicGambarSplatRoute
  '/api/public/google-drive/callback': typeof ApiPublicGoogleDriveCallbackRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/cari'
    | '/admin/drive'
    | '/admin/iklan'
    | '/admin/komentar'
    | '/kategori/$slug'
    | '/tag/$slug'
    | '/admin/'
    | '/admin/tulis/$id'
    | '/api/public/gambar/$'
    | '/api/public/google-drive/callback'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/cari'
    | '/admin/drive'
    | '/admin/iklan'
    | '/admin/komentar'
    | '/kategori/$slug'
    | '/tag/$slug'
    | '/admin'
    | '/admin/tulis/$id'
    | '/api/public/gambar/$'
    | '/api/public/google-drive/callback'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/cari'
    | '/admin/drive'
    | '/admin/iklan'
    | '/admin/komentar'
    | '/kategori/$slug'
    | '/tag/$slug'
    | '/admin/'
    | '/admin/tulis/$id'
    | '/api/public/gambar/$'
    | '/api/public/google-drive/callback'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRouteWithChildren
  CariRoute: typeof CariRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  TagSlugRoute: typeof TagSlugRoute
  ApiPublicGambarSplatRoute: typeof ApiPublicGambarSplatRoute
  ApiPublicGoogleDriveCallbackRoute: typeof ApiPublicGoogleDriveCallbackRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari': {
      id: '/cari'
      path: '/cari'
      fullPath: '/cari'
      preLoaderRoute: typeof CariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drive': {
      id: '/admin/drive'
      path: '/drive'
      fullPath: '/admin/drive'
      preLoaderRoute: typeof AdminDriveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iklan': {
      id: '/admin/iklan'
      path: '/iklan'
      fullPath: '/admin/iklan'
      preLoaderRoute: typeof AdminIklanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/komentar': {
      id: '/admin/komentar'
      path: '/komentar'
      fullPath: '/admin/komentar'
      preLoaderRoute: typeof AdminKomentarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tulis/$id': {
      id: '/admin/tulis/$id'
      path: '/tulis/$id'
      fullPath: '/admin/tulis/$id'
      preLoaderRoute: typeof AdminTulisIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/gambar/$': {
      id: '/api/public/gambar/$'
      path: '/api/public/gambar/$'
      fullPath: '/api/public/gambar/$'
      preLoaderRoute: typeof ApiPublicGambarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-drive/callback': {
      id: '/api/public/google-drive/callback'
      path: '/api/public/google-drive/callback'
      fullPath: '/api/public/google-drive/callback'
      preLoaderRoute: typeof ApiPublicGoogleDriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDriveRoute: typeof AdminDriveRoute
  AdminIklanRoute: typeof AdminIklanRoute
  AdminKomentarRoute: typeof AdminKomentarRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTulisIdRoute: typeof AdminTulisIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDriveRoute: AdminDriveRoute,
  AdminIklanRoute: AdminIklanRoute,
  AdminKomentarRoute: AdminKomentarRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTulisIdRoute: AdminTulisIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRouteWithChildren,
  CariRoute: CariRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  TagSlugRoute: TagSlugRoute,
  ApiPublicGambarSplatRoute: ApiPublicGambarSplatRoute,
  ApiPublicGoogleDriveCallbackRoute: ApiPublicGoogleDriveCallbackRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
